QaA/QaA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ask/', include("ask.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QaA/ask/urls.py
from django.urls import path
from django.contrib.auth.views import TemplateView
from django.contrib.sitemaps.views import sitemap

from . import views
from .view import FriendsViews as friends
from .sitemaps import *


sitemaps = {
    'static': StaticViewSitemap,
}

app_name = "ask"
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.CustomLoginView.as_view(
        template_name='ask/login.html'), name='login'),
    path('logout', views.CustomLogoutView.as_view(
        template_name='ask/logout.html'), name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),

    path('terms', TemplateView.as_view(
         template_name='ask/terms.html'), name='terms'),
    path('privacypolicy', TemplateView.as_view(
        template_name='ask/privacypolicy.html'), name='privacypolicy'),

    path('profile', views.ProfileView.as_view(), name='profile'),
    path('user/<str:username>', views.UserView.as_view(), name='user'),
    path('unanswered', views.UnansweredView.as_view(), name='unanswered'),
    path('settings', views.SettingsView.as_view(), name='settings'),

    path('friends/recent', friends.FriendsRecent.as_view(), name='friends.recent'),
    path('friends/alph', friends.FriendsAlphabetical.as_view(), name='friends.alph'),
    path('friends/inv', friends.FriendsInvitationList.as_view(), name='friends.inv'),
    path('friends/accept', friends.FriendAcceptedView.as_view(),
         name='friends.accept'),
    path('friends/search', friends.FriendSearchView.as_view(), name='friends.search'),
    path('friends', friends.FriendsBase.as_view(), name='friends'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemaps')
]

QaA/ask/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import pathlib


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/avatar<extension>
    fileextension = pathlib.Path(filename).suffix
    # print('filename = ', filename)
    # print('path = ', pathlib.Path(filename))
    # print('avatar.png', 'avatar' + fileextension)
    return 'user_id_{0}_{1}/{2}'.format(instance.id, instance.username, 'avatar' + fileextension)


class UserModel(AbstractUser):
    friends = models.ManyToManyField(
        'self', through='FriendsModel', symmetrical=False)
    avatar = models.ImageField(null=True, upload_to=user_directory_path)


class FriendsModel(models.Model):
    first = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    second = models.ForeignKey(
        UserModel, on_delete=models.CASCADE, related_name="friends_second")
    date = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)


class AnswerModel(models.Model):
    content = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)


class QuestionModel(models.Model):
    owner = models.ForeignKey(
        UserModel, on_delete=models.CASCADE, related_name="questions_owner")
    asked_by = models.ForeignKey(
        UserModel, on_delete=models.PROTECT, related_name="questions_asked")
    content = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    answer = models.OneToOneField(
        AnswerModel, null=True, on_delete=models.CASCADE)

QaA/ask/forms.py
from django import forms

from .fields import *


class SignUpForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    username = UsernameField(max_length=20, required=True)
    password = PasswordField(min_length=6, required=True,
                             error_messages={"min_length": "Password to short. Must be at least 6 characters long"})
    password_repeat = forms.CharField(required=True)
    email = EmailField(required=True)
    terms = forms.BooleanField(required=True, error_messages={
                               "required": "You must agree to Terms of Service"})
    privacy = forms.BooleanField(required=True, error_messages={
        "required": "You must agree to Privacy policy"})

    def clean_password(self):
        try:
            password = self.cleaned_data['password']

            validator = SimilarityValidator(max_similarity=0.5)
            validator.validate(
                password, user=self.cleaned_data)
        except ValidationError as e:
            raise forms.ValidationError(str(e)[2:-2])
        except KeyError:
            return None
        return password

    def clean_password_repeat(self):
        try:
            password = self.cleaned_data['password']
            password_repeat = self.cleaned_data['password_repeat']
        except KeyError:
            return None

        if password != password_repeat:
            raise forms.ValidationError('Password does not match')
        return password_repeat


class QuestionForm(forms.Form):
    question_content = forms.CharField(max_length=1000, required=False)
    action = forms.ChoiceField(
        choices=[('ask_question', 'ask_question'),
                 ('add_friend', 'add_friend'),
                 ('remove_friend', 'remove_friend'),
                 ])


class AnswerForm(forms.Form):
    answer_content = forms.CharField(max_length=1000, required=True)
    question_id = forms.IntegerField(required=True)


class FriendAcceptedForm(forms.Form):
    user_id = forms.IntegerField(required=True)


class FriendSearchForm(forms.Form):
    search_text = forms.CharField(max_length=50, required=True)


class ProfileImageForm(forms.Form):
    image = forms.ImageField(required=True)

QaA/ask/views.py
import os

from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.views.generic.base import View
from django.views.generic.edit import FormMixin, FormView

from .forms import AnswerForm, ProfileImageForm, QuestionForm, SignUpForm
from .models import AnswerModel, FriendsModel, UserModel
from .view.MixIns import *


def index(request):
    return render(request, "ask/index.html")


class CustomLoginView(LoginView):

    def form_valid(self, form):
        self.request.session['logged_in'] = True
        self.request.session['username'] = form.cleaned_data['username']
        return super().form_valid(form)


class CustomLogoutView(LogoutView):

    def post(self, request, *args, **kwargs):
        del request['logged_in']
        del request['username']
        super().post(request, *args, **kwargs)


class SignUpView(FormView):
    template_name = 'ask/signup.html'
    form_class = SignUpForm
    success_url = 'profile'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user = self.form_to_model(form)
            user.set_password(form.cleaned_data['password'])
            user.save()
            send_mail("Account created in Questions&Answers",
                      "Thank you for creating account",
                      "from@example.com",
                      [user.email],
                      fail_silently=False)
            self.log_in(user.username, form.cleaned_data['password'], request)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_to_model(self, form):
        clean_data = form.cleaned_data
        userdata = {
            'first_name': clean_data['first_name'],
            'last_name': clean_data['last_name'],
            'username': clean_data['username'],
            'email': clean_data['email'],
        }
        return UserModel(**userdata)

    def log_in(self, username, password, request):
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)

        request.session['logged_in'] = True
        request.session['username'] = username


class ProfileView(View, QuestionsMixIn, FriendsMixIn):

    def get(self, request):
        try:
            user = UserModel.objects.get(
                pk=request.session['_auth_user_id'])
        except KeyError:
            return HttpResponseRedirect(reverse('ask:login'))

        context = self.get_context(user)
        self.add_pagination(context, request)
        return render(request, "ask/profile.html", context=context)

    @QuestionsMixIn.add_num_unanswered_to_context
    @FriendsMixIn.add_num_invites_to_context
    @AvatarMinIn.add_avatar_to_context
    def get_context(self, user):
        questions_with_answers = self.questions_with_answers(
            user)
        context = {"questions_with_answers": questions_with_answers}
        return context

    def add_pagination(self, context, request):
        paginator = Paginator(context["questions_with_answers"], 6)
        page = request.GET.get('page')
        context["questions_with_answers"] = paginator.get_page(page)


class UserView(View, FormMixin, QuestionsMixIn, FriendsMixIn):
    form_class = QuestionForm

    def get(self, request, username):
        context = self.get_context(
            request.session['_auth_user_id'], username)
        return render(request, "ask/user.html", context=context)

    def post(self, request, username):
        form = self.get_form()
        context = self.get_context(
            request.session['_auth_user_id'], username)
        if form.is_valid():
            self.dispatch_action(form.cleaned_data, context,
                                 username, request.session['_auth_user_id'])
        return render(request, "ask/user.html", context=context)

    def dispatch_action(self, cleaned_data, context, username, auth_user_id):
        if cleaned_data['action'] == 'ask_question':
            context['question_submitted'] = "Your question was submitted"
            self.create_question(username, auth_user_id,
                                 cleaned_data['question_content'])
        elif cleaned_data['action'] == 'add_friend':
            context['is_friend'] = True
            self.add_friend(auth_user_id, username)
        elif cleaned_data['action'] == 'remove_friend':
            context['is_friend'] = False
            self.remove_friend(auth_user_id, username)

    @QuestionsMixIn.add_num_unanswered_to_context
    @FriendsMixIn.add_num_invites_to_context
    @AvatarMinIn.add_avatar_to_context
    def get_context(self, logedin_user_id, username):
        viewed_user = UserModel.objects.get(username=username)
        questions_with_answers = self.questions_with_answers(viewed_user)
        is_friend_is_accepted = self.is_friend_is_accepted(
            logedin_user_id, viewed_user)
        context = {
            'username': username,
            'questions_with_answers': questions_with_answers,
            'is_friend': is_friend_is_accepted[0],
            'accepted': is_friend_is_accepted[1],
        }
        return context

    def is_friend_is_accepted(self, logedin_user_id, viewed_user):
        logedin_user = UserModel.objects.get(pk=logedin_user_id)

        try:
            friends = FriendsModel.objects.get(
                first=logedin_user, second=viewed_user)
        except FriendsModel.DoesNotExist:
            try:
                friends = FriendsModel.objects.get(
                    first=viewed_user, second=logedin_user)
            except FriendsModel.DoesNotExist:
                return False, False
            else:
                return True, friends.accepted
        else:
            return True, friends.accepted

    def create_question(self, owner_username, logedin_user_id, content):
        asked_by = UserModel.objects.filter(pk=logedin_user_id)[0]
        owner = UserModel.objects.filter(username=owner_username)[0]
        question = QuestionModel(owner=owner,
                                 asked_by=asked_by,
                                 content=content)
        question.save()

    def add_friend(self, logedin_user_id, username):
        logged_in_user = UserModel.objects.get(pk=logedin_user_id)
        viewed_user = UserModel.objects.get(username=username)
        friend = FriendsModel(first=logged_in_user, second=viewed_user)
        friend.save()

    def remove_friend(self, logedin_user_id, username):
        logged_in_user = UserModel.objects.get(pk=logedin_user_id)
        viewed_user = UserModel.objects.get(username=username)
        FriendsModel.objects.filter(
            first=logged_in_user, second=viewed_user).delete()
        FriendsModel.objects.filter(
            first=viewed_user, second=logged_in_user).delete()


class UnansweredView(View, FormMixin, QuestionsMixIn, FriendsMixIn):
    form_class = AnswerForm

    def get(self, request):
        try:
            user = UserModel.objects.get(
                pk=request.session['_auth_user_id'])
        except KeyError:
            return HttpResponseRedirect(reverse('ask:login'))

        context = self.get_context(user)
        return render(request, 'ask/unanswered.html', context=context)

    @QuestionsMixIn.add_num_unanswered_to_context
    @FriendsMixIn.add_num_invites_to_context
    @AvatarMinIn.add_avatar_to_context
    def get_context(self, user):
        unanswered_questions = self.unanswered_questions(user)
        unanswered_questions = unanswered_questions.order_by('date')[::-1]
        context = {'unanswered_questions': unanswered_questions}
        return context

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            answer = self.create_answer(form.cleaned_data['answer_content'])
            self.attach_answer_to_question(
                answer, form.cleaned_data['question_id'])

        return self.get(request)

    def create_answer(self, content):
        answer = AnswerModel(content=content)
        answer.save()
        return answer

    def attach_answer_to_question(self, answer, user_id):
        question = QuestionModel.objects.get(id=user_id)
        question.answer = answer
        question.save()


class SettingsView(FormView, QuestionsMixIn, FriendsMixIn):
    template_name = 'ask/settings.html'
    form_class = ProfileImageForm
    success_url = 'settings'

    def get(self, request):
        try:
            user = UserModel.objects.get(
                pk=request.session['_auth_user_id'])
        except KeyError:
            return HttpResponseRedirect(reverse('ask:login'))

        context = self.get_context(user)
        return render(request, 'ask/settings.html', context=context)

    @QuestionsMixIn.add_num_unanswered_to_context
    @FriendsMixIn.add_num_invites_to_context
    @AvatarMinIn.add_avatar_to_context
    def get_context(self, user):
        context = {}
        return context

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            user = self.get_logged_in_user(request)
            self.remove_old_avatar(user)
            user.avatar = form.cleaned_data['image']
            user.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_logged_in_user(self, request):
        user_id = request.session['_auth_user_id']
        user = UserModel.objects.get(pk=user_id)
        return user

    def remove_old_avatar(self, user):
        if user.__dict__['avatar']:
            user.avatar.delete(save=True)

QaA/ask/templates/ask/friends.html
{% extends "ask/navigation_bar.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'ask/navigation_bar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/questions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/friends.css' %}">
{% endblock styles %}

{% block content %}
<div class="questions">
    <div class="question_block">
        <div class="menu">
            <a href="{% url 'ask:friends.recent' %}" class="item">Recently added</a>
            <a href="{% url 'ask:friends.alph' %}" class="item">Alphabetical order</a>
            <a href="{% url 'ask:friends.inv' %}" class="item">Invitations</a>
            <a></a>
            <form method="POST" action="{% url 'ask:friends.search' %}">
                {% csrf_token %}
                <a class="search_text">Search: </a>
                <input type="textarea" class="search" id="search_text" name="search_text" required>
            </form>
        </div>
        <hr>
        {% if show_invites %}
        <div class="friends_container">
            {% if invitations|length > 0 %}
            {% for user in invitations %}
            <div class="friend">
                {% if user.avatar %}
                <img src="{{ user.avatar.url }}" class="nav_avatar">
                {% else %}
                <img src="{% static 'ask/default.png' %}" class="avatar">
                {% endif %}
                <br><a class="username">{{user.username}}</a>
                <form method="POST" action="{% url 'ask:friends.accept' %}">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value={{user.id}}>
                    <input type="submit" class="accept" value="Accept" required>
                </form>
            </div>
            {% endfor %}
            {% else %}
            <p class="message">You have no new invitations</p>
            {% endif %}
        </div>
        {% else %}
        <div class="friends_container">
            {% if friends|length > 0 %}
            {% for friend in friends %}
            <div class="friend">
                {% if friend.avatar %}
                <img src="{{ friend.avatar.url }}" class="nav_avatar">
                {% else %}
                <img src="{% static 'ask/default.png' %}" class="avatar">
                {% endif %}
                <br><a class="username" href="{% url 'ask:user' friend.username %}">{{friend.username}}</a>
            </div>
            {% endfor %}
            {% else %}
            <p class="message">You have no friends yet</p>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

QaA/ask/templates/ask/index.html
{% extends "ask/login_bar.html" %}

QaA/ask/templates/ask/login.html
{%load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Log In | QuestionAndAnswers</title>
    <link rel="stylesheet" type="text/css" href="{% static 'ask/login.css' %}">
</head>

<body>
    <main class="login">
        <form method="POST" action="{% url 'ask:login' %}">
            {% csrf_token %}
            <label for="login">Username:</label>
            <br>
            <input type="text" id="login" name="username">
            <br>
            <label for="password">Password:</label>
            <br>
            <input type="password" id="Password" name="password">
            {% if form.errors %}
            <p class="error">Wrong username or password. Please try again.</p>
            {% endif %}
            <br>
            <input class="button" type="submit" value="Log In">
            <input class="button" type="button" value="Forget Password">
        </form>
        <a href="{% url 'ask:index' %}" class="back_to_main">&larr; back to main page</a>
    </main>
</body>

</html>

QaA/ask/templates/ask/login_bar.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    {% block site_title %}
    <title>Questions and Answers</title>
    {% endblock site_title %}
    <link rel="stylesheet" type="text/css" href="{% static 'ask/login_bar.css' %}">
    {% block styles %}
    {% endblock styles %}
</head>

<body>
    <div class="bar">
        <a class="logo" href="{% url 'ask:index' %}">Questions & Answers</a>
        <a></a>
        {% if request.session.logged_in %}
        <a class="logged_in_as">Logged in as: <b>{{request.session.username}}</b></a>
        <a href={% url "ask:logout" %}><input type="button" class="second_button" value="Log Out"></a>
        {% else %}
        <a href={% url "ask:login" %}><input type="button" class="first_button" value="Log In"></a>
        <a href={% url "ask:signup" %}><input type="button" class="second_button" value="Sign Up"></a>
        {% endif %}
    </div>
    <br>
    <main>
        {% block content %}
        <h1>Welcome to Questions and Answers</h1>
        <p>Site where you can find all the answers</p>
        {% endblock content %}
        {% block nav %}

        {% endblock nav %}
    </main>
</body>

</html>

QaA/ask/templates/ask/logout.html
{% extends "ask/login_bar.html" %}

{% block site_title %}
<title>Logged Out</title>
{% endblock site_title %}

{% block content %}
<p>Logged out sucessfully</p>
<p>Go back to the <a href="./">main page</a> or <a href="login">log in</a> again.</p>
{% endblock content %}

QaA/ask/templates/ask/navigation_bar.html
{% extends "ask/login_bar.html" %}
{% load static %}

{%block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'ask/navigation_bar.css' %}">
{% endblock styles %}

{% block nav %}
<nav>
    <div class="nav_avatar_position">
        {% if user_avatar %}
        <img src="{{ user_avatar.url }}" class="nav_avatar">
        {% else %}
        <img src="{% static 'ask/default.png' %}" class="nav_avatar">
        {% endif %}
        <p class="nav_username">{{request.session.username}}</p>
        <hr class="nav_line">
    </div>
    <a href="{% url 'ask:profile' %}">My Profile</a>
    {% if num_unanswered > 0 %}
    <a href="{% url 'ask:unanswered' %}">Unanswered questions({{num_unanswered}})</a>
    {% else %}
    <a href="{% url 'ask:unanswered' %}">Unanswered questions</a>
    {% endif %}
    {% if num_invites %}
    <a href="{% url 'ask:friends' %}">Friends({{num_invites}})</a>
    {% else %}
    <a href="{% url 'ask:friends' %}">Friends</a>
    {% endif %}
    <a href="{% url 'ask:settings' %}">Settings</a>
</nav>
{% endblock nav %}

QaA/ask/templates/ask/privacypolicy.html
<p>Privacy policy placeholder</p>

QaA/ask/templates/ask/profile.html
{% extends "ask/navigation_bar.html" %}
{% load static %}

{% block site_title %}
<title>Profile</title>
{% endblock site_title %}

{%block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'ask/navigation_bar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/questions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/profile.css' %}">
{% endblock styles %}

{%block content %}
<div class="questions">
    {% if questions_with_answers|length == 0 %}
    <div class="question_block">
        <p class="no_unanswered">No questions yet</p>
    </div>
    {% else %}
    {% for question, answer in questions_with_answers %}
    <div class="question_block">
        <a class="asked_by">Asked by: {{ question.asked_by.username }}</a>
        <a class="asked_date"> {{ question.date }} </a>
        <p class="question">{{ question.content }}</p>
        <p class="answer">{{ answer.content }}</p>
    </div>
    {% endfor %}
    <div class="pagination">
        {% if questions_with_answers.has_previous %}
        <a href="?page=1" class="pagination_item">first</a>
        <a href="?page={{questions_with_answers.previous_page_number }}" class="pagination_item">previous</a>
        {% else %}
        <a class="pagination_item">first</a>
        <a class="pagination_item">previous</a>
        {% endif %}
        <span class="pagination_item">
            Page {{questions_with_answers.number}} of {{questions_with_answers.paginator.num_pages}}
        </span>
        {% if questions_with_answers.has_next %}
        <a href="?page={{questions_with_answers.next_page_number}}" class="pagination_item">next</a>
        <a href="?page={{questions_with_answers.paginator.num_pages}}" class="pagination_item">last</a>
        {% else %}
        <a class="pagination_item">next</a>
        <a class="pagination_item">last</a>
        {%endif%}
    </div>
    {% endif %}
</div>
{% endblock content %}

QaA/ask/templates/ask/settings.html
{% extends "ask/navigation_bar.html" %}
{% load static %}

{% block site_title %}
<title>Profile</title>
{% endblock site_title %}

{%block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'ask/navigation_bar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/questions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/settings.css' %}">
{% endblock styles %}

{%block content %}
<div class="questions">
    <div class="question_block">
        <h4 class="section">Change profile picture</h4>
        <form method="POST" class="profile_pic" enctype="multipart/form-data" action="{% url 'ask:settings' %}">
            {% csrf_token %}
            <input type="file" class="img_select" name="image" accept="image/*" required>
            {{ form.image.errors }}
            <br>
            <input type="submit" class="img_select" value="Upload" required>
        </form>
    </div>
</div>
{% endblock content %}

QaA/ask/templates/ask/signup.html
{%load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Sign Up | QuestionAndAnswers</title>
    <link rel="stylesheet" type="text/css" href="{% static 'ask/signup.css' %}">
</head>

<body>
    <main class="signup">
        <form method="POST" action="{% url 'ask:signup' %}">
            {% csrf_token %}
            <label for="first_name">First name:</label>
            {{ form.first_name.errors }}
            <br>
            <input type="text" id="first_name" name="first_name">
            <br>
            <label for="last_name">Last name:</label>
            {{ form.last_name.errors }}
            <br>
            <input type="text" id="last name" name="last_name">
            <br>
            <label for="login">Username:</label>
            {{ form.username.errors }}
            <br>
            <input type="text" id="login" name="username">
            <br>
            <label for="email">Email:</label>
            {{ form.email.errors }}
            <br>
            <input type="email" id="email" name="email">
            <br>
            <label for="password">Password:</label>
            {{ form.password.errors }}
            <br>
            <input type="password" id="password" name="password">
            <br>
            <label for="password_repeat">Repeat password:</label>
            {{ form.password_repeat.errors }}
            <br>
            <input type="password" id="password_repeat" name="password_repeat">
            <br>
            <input type="checkbox" id="terms" name="terms">
            <label for="terms" class="consent">I accept the <a href="terms">Terms of Service</a></label>
            {{ form.terms.errors }}
            <br>
            <input type="checkbox" id="privacy" name="privacy">
            <label for="privacy" class="consent">I have read and agree to the <a href="privacypolicy">Privacy
                    policy</a></label>
            {{ form.privacy.errors }}
            <br>
            <input class="button" type="submit" value="Sign Up">
        </form>
    </main>
</body>

</html>

QaA/ask/templates/ask/terms.html
<p>Terms of service placeholder</p>

QaA/ask/templates/ask/unanswered.html
{% extends "ask/navigation_bar.html" %}
{% load static %}

{%block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'ask/navigation_bar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/questions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/unanswered.css' %}">
{% endblock styles %}

{% block content %}
<div class="questions">
    {% if unanswered_questions %}
    {% for question in unanswered_questions %}
    <div class="question_block">
        <a class="asked_by">Asked by: {{ question.asked_by.username }}</a>
        <a class="asked_date"> {{ question.date }} </a>
        <p class="question">{{ question.content }}</p>
        <form method="POST" action="{% url 'ask:unanswered' %}">
            {% csrf_token %}
            <input type="text" class="answer_textbox" name="answer_content" required>
            <input type="hidden" name="question_id" value={{question.id}} required>
            <input type="submit" class="answer_submit" value="Answer">
        </form>
    </div>
    {% endfor %}
    {% else %}
    <div class="question_block">
        <p class="no_unanswered">No unanswered questions</p>
    </div>
    {% endif %}
</div>
{% endblock content %}

QaA/ask/templates/ask/user.html
{% extends "ask/navigation_bar.html" %}
{% load static %}

{%block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'ask/navigation_bar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/questions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'ask/user.css' %}">
{% endblock styles %}

{% block content %}
<div class="questions">
    <div class="question_user_block">
        <img src="{% static 'ask/default.png' %}" class="avatar">
        <p class="username">{{username}} profile</p>
        {% if not is_friend %}
        <form method="POST" class="add_to_friends_form" action="{% url 'ask:user' username %}">
            {% csrf_token %}
            <input type="submit" class="add_to_friends" value="Add to friends">
            <input type="hidden" name="action" value="add_friend" required>
        </form>
        {% else %}
        {% if not accepted %}
        <p class="sent">Your invitation have been sent</p>
        {% else %}
        <form method="POST" class="add_to_friends_form" action="{% url 'ask:user' username %}">
            {% csrf_token %}
            <input type="submit" class="add_to_friends" value="Remove from friends">
            <input type="hidden" name="action" value="remove_friend" required>
        </form>
        {% endif %}
        {% endif %}
    </div>
    {% if request.session.logged_in %}
    <div class="ask_question">
        <form method="POST" action="{% url 'ask:user' username %}">
            {% csrf_token %}
            <a class="prompt">Ask some question:</a>
            <input type="textarea" class="question_textbox" id="question_content" name="question_content" required>
            <br>
            <input type="hidden" name="action" value="ask_question" required>
            <input type="submit" class="question_submit" value="Ask">
        </form>
    </div>
    <div class="bar_placeholder"></div>
    {% endif %}
    <div class="questions">
        {% for question, answer in questions_with_answers %}
        <div class="question_block">
            <a class="asked_by">Asked by: {{ question.asked_by.username }}</a>
            <a class="asked_date"> {{ question.date }} </a>
            <p class="question">{{ question.content }}</p>
            <p class="answer">{{ answer.content }}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}